---
title: "01-carbon-emissions-and-food"
author: "Florence Galliers"
date: "17/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(extrafont)
#font_import()
library(plyr)
library(countrycode)
library(dplyr)
```

## Introduction

This dataset contains information about 130 countries, their consumption and emissions of 11 types of food.


```{r }
food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')

# How many countries?
unique(food_consumption$country)
# 130

# How many food categories?
unique(food_consumption$food_category)
# 11

# calculate total co2 emissions for each country
footprint_total <- food_consumption %>%
  dplyr::select(country, co2_emmission) %>%
  group_by(country) %>%
  dplyr::summarise(total = sum(co2_emmission))

# calculate total consumption for each country
consumption_total <- food_consumption %>%
  dplyr::select(country, consumption) %>%
  group_by(country) %>%
  dplyr::summarise(total = sum(consumption))

totals <- merge(footprint_total, consumption_total,
                by = "country")
colnames(totals) <- c("country", "footprint", "consumption")

totals$difference <- totals$footprint - totals$consumption
head(totals)

# Biggest differences between consumption and emissions, both positive and negative?
tail(sort(totals$difference), 5)
head(sort(totals$difference), 5)

top10 <- totals %>%
  filter(totals$difference >= (tail(sort(totals$difference), 5))[1] | 
           totals$difference <= (head(sort(totals$difference), 5))[5])

dotchart(sort(top10$difference), top10$country,
     pch = 16,
     col = "red")


```

Consumption per food category worldwide?
So which food category is most popular 

```{r}
# make category a factor
food_consumption$food_category <- factor(food_consumption$food_category)
levels(food_consumption$food_category)
# rename some of the levels
food_consumption$food_category <- revalue(food_consumption$food_category,
        c("Lamb & Goat" = "Lamb/Goat",
          "Milk - inc. cheese" = "Dairy",
          "Nuts inc. Peanut Butter" = "Nuts",
          "Wheat and Wheat Products" = "Wheat"))

# I want to colour the points by continent. so need to add a new column to the data called continent.

food_consumption$continent <- countrycode(food_consumption$country, 'country.name', 'continent')
continents <- unique(food_consumption$continent) # five continents here

# create colour palette of 5 colours

palette <- c("#ef476f", "#ffd166", "#06d6a0", "#118ab2", "#073b4c")

colour_frame <- data.frame(continents, palette)

food_plot <- merge(food_consumption, colour_frame,
      by.x = "continent",
      by.y = "continents",
      all.x = T)

food_plot$continent <- as.factor(food_plot$continent)

#names(food_plot)[names(food_plot) == "palette"] <- "pal"
# make colour palette
#levels(food_plot$continent)
#color_pallete_function <- colorRampPalette(
#  colors = c("#ef476f", "#ffd166", "#06d6a0", "#118ab2", "#073b4c"))
#num_colors <- nlevels(food_plot$continent)
#food_color_colors <- color_pallete_function(num_colors)

set.seed(42)
# boxplot of food consumption
boxplot(consumption ~ reorder(food_category, consumption), 
        data = food_plot,
        outline = F,
        pch = 1,
        xlim = c(0.5, 11.5),
        ylim = c(0, 350),
        col = "white",
        medcol = "grey60", whiskcol = "grey60", 
        staplecol = "grey60", boxcol = "grey60", outcol = "grey60")
# add stripcharts for each continent
stripchart(consumption ~ reorder(food_category, consumption), 
           data = filter(food_plot, continent == "Africa"), 
           col = alpha(palette[1], 0.5), vertical = T,
           method = "jitter", add = T, at = 0.8:10.8,
           pch = 16, ylim = c(0, 450))
stripchart(consumption ~ reorder(food_category, consumption), 
           data = filter(food_plot, continent == "Americas"), 
           col = alpha(palette[2], 0.5), vertical = T,
           method = "jitter", add = T, at = 0.9:10.9,
           pch = 16)
stripchart(consumption ~ reorder(food_category, consumption), 
           data = filter(food_plot, continent == "Asia"), 
           col = alpha(palette[3], 0.5), vertical = T,
           method = "jitter", add = T, at = 1:11,
           pch = 16)
stripchart(consumption ~ reorder(food_category, consumption), 
           data = filter(food_plot, continent == "Europe"), 
           col = alpha(palette[4], 0.5), vertical = T,
           method = "jitter", add = T, at = 1.1:11.1,
           pch = 16)
stripchart(consumption ~ reorder(food_category, consumption), 
           data = filter(food_plot, continent == "Oceania"), 
           col = alpha(palette[5], 0.5), vertical = T,
           method = "jitter", add = T, at = 1.2:11.2,
           pch = 16)
legend(
  x ="topleft",
  legend = paste(levels(food_plot$continent)),
  col = alpha(palette, 0.5),
  pch = 16, 
  cex = 1)



```

Battle of the animals
- Which meat is consumed most widely across the world, and which contributes the most CO2 emissions?

```{r}
# filter the dataset to only contain meat categories:
meat <- food_consumption %>%
  filter(food_category == "Pork" | food_category == "Poultry" | food_category == "Beef" | food_category == "Lamb/Goat" | food_category == "Fish")

# convert food categories to factors
meat$food_category <- as.factor(meat$food_category)

# test plot to see consumption vs category
ggplot(meat, 
       aes(x = reorder(food_category, consumption), 
           y = consumption)) +
  geom_bar(stat = "identity") +
  coord_flip()
  
# what about combining consumption and emissions onto one plot?
# first need to tidy data
meat_tidy <- meat %>%
  pivot_longer(names(meat)[3:4],
               names_to = "type",
               values_to = "kg")

# test plot to compare consumption and emissions of different types of meat
ggplot(meat_tidy, 
       aes(fill = type, x = food_category, y = kg)) +
  geom_bar(stat = "identity",
           position = "dodge") +
  coord_flip()
# can see there is a massive difference between the two
# looks fine but maybe using the 'difference' category would be better.
ggplot(meat, 
       aes(x = reorder(food_category, difference), 
           y = difference)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "",
       subtitle = "The difference between consumption of meat (kg/person/year) 
and their carbon emissions (kg CO2/person/year) worldwide")

# subset for each type of meat and find the highest value
beef <- meat %>%
  filter(food_category == "Beef")
beef[which.max(beef$co2_emmission), ]
argentina_value <- as.numeric(beef[which.max(beef$co2_emmission), 4])

lamb <- meat %>%
  filter(food_category == "Lamb/Goat")
lamb[which.max(lamb$co2_emmission), ]
iceland_value <- as.numeric(lamb[which.max(lamb$co2_emmission), 4])

fish <- meat %>%
  filter(food_category == "Fish")
fish[which.max(fish$co2_emmission), ]
maldives_value <- as.numeric(fish[which.max(fish$co2_emmission), 4])

pork <- meat %>%
  filter(food_category == "Pork")
pork[which.max(pork$co2_emmission), ]
hongkong_value <- as.numeric(pork[which.max(pork$co2_emmission), 4])

# remove these values from the meat_edit dataset
meat_edit <- meat[-(which(meat$co2_emmission == argentina_value | 
        meat$co2_emmission == iceland_value |
        meat$co2_emmission == maldives_value |
        meat$co2_emmission == hongkong_value)), ]

# subset each value into its own data frame so it can be plotted separately.
argentina <- meat %>%
  filter(country == "Argentina" & food_category == "Beef")
# Iceland - Lamb/Goat
iceland <- meat %>%
  filter(country == "Iceland" & food_category == "Lamb/Goat")
# Maldives - Fish
maldives <- meat %>%
  filter(country == "Maldives" & food_category == "Fish")
# Hong Kong - Pork
hongkong <- meat %>%
  filter(country == "Hong Kong SAR. China" & food_category == "Pork")

# Plot a strip chart
plot1 <- ggplot(meat_edit, 
       aes(x = reorder(food_category, co2_emmission), 
           y = co2_emmission, 
           size = consumption)) +
  geom_point(position = position_jitter(seed = 41),
             colour = "grey70") +
  coord_flip() +
  labs(title = "Argentina emits the most CO2 from beef...",
       subtitle = "...what about other animal products?",
       size = "Each circle represents a country,\nsized by quantity (kg/person/year) of\neach meat supplied for consumption") +
  ylab("CO2 emissions (kg CO2/person/year)") +
  scale_x_discrete(labels = c("POULTRY", "FISH", "PORK", "LAMB/GOAT", "BEEF")) +
  theme(plot.title = element_text(family = "Avenir", 
                                  size = 16, 
                                  colour = "#840a35"),
        plot.subtitle = element_text(family = "Avenir",
                                     size = 12),
        axis.title.y = element_blank(),
        axis.title.x = element_text(family = "Avenir",
                                    size = 8),
        plot.background = element_rect(fill = "#f1f1f1"),
        panel.background = element_rect(fill = "#f1f1f1"),
        panel.grid = element_blank(),
        axis.ticks = element_blank(),
        axis.text.y = element_text(angle = 90, hjust=0.5, vjust = -6,
                                   face = "bold", size = 10, 
                                   family = "Avenir"),
        axis.text.x = element_text(family = "Avenir"),
        legend.position = c(0.85, 0.4),
        legend.text = element_text(family = "Avenir",
                                   size = 8),
        legend.title = element_text(family = "Avenir",
                                    size = 8),
        legend.background = element_blank(),
        legend.direction = "horizontal") +
  guides(size = guide_legend(reverse=TRUE,
                             title.position = "top", 
                             title.hjust = 0.5,
                             label.position = "bottom",
                             override.aes=list(colour="grey70"))) +
  geom_point(data = argentina, position = position_jitter(seed = 41), 
             colour = "#840a35") +
  geom_point(data = iceland, position = position_jitter(seed = 41), 
             colour = "purple") +
  geom_point(data = hongkong, position = position_jitter(seed = 36), 
             colour = "orange") +
  geom_point(data = maldives, position = position_jitter(seed = 41), 
             colour = "royalblue") + 
  # argentina text
  annotate("text", x = 4.77, y = 1600,
           label = "ARGENTINA",
           colour = "#840a35",
           size = 4,
           family = "Avenir") +
  # iceland text
  annotate("text", x = 3.77, y = 820,
           label = "ICELAND",
           colour = "purple",
           size = 4,
           family = "Avenir") +
  # hong kong text
  annotate("text", x = 3.1, y = 350,
           label = "HONG KONG",
           colour = "orange",
           size = 4,
           family = "Avenir") +  
  # maldives text
  annotate("text", x = 1.77, y = 380,
           label = "MALDIVES",
           colour = "royalblue",
           size = 4,
           family = "Avenir")

plot1

```


```{r}
# subset dairy category into its own object
dairy <- food_consumption %>%
  filter(food_category == "Dairy") %>%
  dplyr::select(country, consumption)

library(sf)
library(viridis)
library(rnaturalearth)

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

world_dairy <- st_as_sf(merge(dairy, world,
                     by.x = "country",
                     by.y = "name",
                     all.x = TRUE))

europe_dairy <- world_dairy %>%
  subset(continent == "Europe")

europe_labels <- europe_dairy %>%
  dplyr::select(country, geometry, consumption) %>%
  filter(country != "Russia")

finland_label <- europe_labels %>%
  filter(country == "Finland")

belarus_label <- europe_labels %>%
  filter(country == "Belarus")


set.seed(41)

ggplot(data = europe_dairy) +
  geom_sf(aes(fill = consumption), color = "grey30") +
  labs(title = "") +
  scale_fill_viridis(option = "D", na.value = "grey80",
                     direction = -1,
                     guide = guide_colourbar(),
                     breaks = c(150, 200, 250, 300, 350, 400),
                     labels = c("150kg/person/year", "200", "250", "300", "350", "400")) +
  coord_sf(xlim = c(-25.5, 32.87), ylim = c(30.15, 69.5), expand = FALSE,
           clip = "off") +
  theme_void() +
  ggrepel::geom_label_repel(data = europe_labels, 
                            aes(label = country, geometry = geometry#, fill = consumption
                                ),
                            stat = "sf_coordinates",
                size = 3,
                min.segment.length = 10,
                color = "grey25",
                family = "American Typewriter") +
  # add subtitle for finland
  geom_label(data = finland_label, 
               aes(label = country, fill = consumption), 
               x = -18, y = 55.5,
                size = 5,
             label.padding = unit(0.2, "cm"),
                color = "white",
             family = "American Typewriter") +
    geom_label(data = belarus_label, 
               aes(label = country, fill = consumption), 
               x = -18, y = 43.7,
                size = 5,
             label.padding = unit(0.2, "cm"),
                color = "gray30",
             family = "American Typewriter") +
  theme(
    legend.position = c(0.15, 0.5),
    legend.direction = "vertical",
    legend.title = element_blank(),
    legend.text = element_text(family = "American Typewriter",
                               size = 7)
  ) +
  annotate("text",
           x = -18,
           y = 60,
           label = "Who consumes the most\ndairy products?",
           family = "American Typewriter",
           size = 7) +
  guides(fill = guide_colorbar(barwidth = 1, 
                               barheight = 10))

finland_label


#mypalette <- colorNumeric( palette="magma",
#                           domain=world_dairy$consumption, na.color="transparent")

#leaflet(world_dairy) %>%
#  addTiles() %>%
#  addPolygons(fillColor = ~mypalette(consumption), stroke = F)


```

